Fix TypeError exception when printing Album contents
The print_album() function tries to instantiate an Album object twice, passing
an object in where a dictionary is expected and throwing a "TypeError: 'Album'
object has no attribute '__getitem__'" exception.

Committing this micro-fix by itself because test.py is typically used as an
example for new code.